# Generated by Django 3.1.6 on 2021-02-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListElement',
            new_name='Element',
        ),
    ]
